
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analyser;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int WRITE_HEAP = 25;
  public static final int GENERATE_RSA_KEY_PAIR = 27;
  public static final int CLOSE_FILE = 16;
  public static final int READ_HEAP = 13;
  public static final int OPEN_FILE = 14;
  public static final int BINOPPRIORITY2 = 38;
  public static final int BINOPPRIORITY1 = 37;
  public static final int BUNOP = 20;
  public static final int DECRYPT_RSA = 29;
  public static final int UNOP = 30;
  public static final int FOR = 11;
  public static final int REF = 24;
  public static final int WRITE = 18;
  public static final int WRITE_FILE = 17;
  public static final int STRINGCONST = 33;
  public static final int BBINOP = 35;
  public static final int SEMICOLON = 2;
  public static final int RPAR = 5;
  public static final int READ_FILE = 15;
  public static final int TYPE = 40;
  public static final int INTCONST = 31;
  public static final int REFERENCE = 36;
  public static final int COMMA = 3;
  public static final int READ_INTEGER = 12;
  public static final int COMP = 34;
  public static final int BEGIN = 6;
  public static final int CHANGE_STATUS = 26;
  public static final int ASSIGN = 21;
  public static final int IF = 8;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int ENCRYPT_RSA = 28;
  public static final int IDENT = 32;
  public static final int ALLOCATE_AT = 23;
  public static final int ELSE = 9;
  public static final int GOTO = 22;
  public static final int WHILE = 10;
  public static final int BOOLCONST = 39;
  public static final int END = 7;
  public static final int LPAR = 4;
  public static final int PRINT = 19;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMICOLON",
  "COMMA",
  "LPAR",
  "RPAR",
  "BEGIN",
  "END",
  "IF",
  "ELSE",
  "WHILE",
  "FOR",
  "READ_INTEGER",
  "READ_HEAP",
  "OPEN_FILE",
  "READ_FILE",
  "CLOSE_FILE",
  "WRITE_FILE",
  "WRITE",
  "PRINT",
  "BUNOP",
  "ASSIGN",
  "GOTO",
  "ALLOCATE_AT",
  "REF",
  "WRITE_HEAP",
  "CHANGE_STATUS",
  "GENERATE_RSA_KEY_PAIR",
  "ENCRYPT_RSA",
  "DECRYPT_RSA",
  "UNOP",
  "INTCONST",
  "IDENT",
  "STRINGCONST",
  "COMP",
  "BBINOP",
  "REFERENCE",
  "BINOPPRIORITY1",
  "BINOPPRIORITY2",
  "BOOLCONST",
  "TYPE"
  };
}

