
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analyser;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int IDENT = 24;
  public static final int SEMICOLON = 2;
  public static final int ELSE = 9;
  public static final int STRINGCONST = 25;
  public static final int COMP = 26;
  public static final int GOTO = 20;
  public static final int WHILE = 10;
  public static final int END = 7;
  public static final int INTCONST = 23;
  public static final int BBINOP = 27;
  public static final int IF = 8;
  public static final int READ_INTEGER = 12;
  public static final int WRITE = 17;
  public static final int BEGIN = 6;
  public static final int TYPE = 21;
  public static final int COMMA = 3;
  public static final int EOF = 0;
  public static final int CLOSE_FILE = 16;
  public static final int BINOPPRIORITY2 = 29;
  public static final int READ_FILE = 15;
  public static final int BINOPPRIORITY1 = 28;
  public static final int BUNOP = 18;
  public static final int error = 1;
  public static final int OPEN_FILE = 14;
  public static final int ASSIGN = 19;
  public static final int READ_HEAP = 13;
  public static final int RPAR = 5;
  public static final int FOR = 11;
  public static final int LPAR = 4;
  public static final int BOOLCONST = 30;
  public static final int UNOP = 22;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMICOLON",
  "COMMA",
  "LPAR",
  "RPAR",
  "BEGIN",
  "END",
  "IF",
  "ELSE",
  "WHILE",
  "FOR",
  "READ_INTEGER",
  "READ_HEAP",
  "OPEN_FILE",
  "READ_FILE",
  "CLOSE_FILE",
  "WRITE",
  "BUNOP",
  "ASSIGN",
  "GOTO",
  "TYPE",
  "UNOP",
  "INTCONST",
  "IDENT",
  "STRINGCONST",
  "COMP",
  "BBINOP",
  "BINOPPRIORITY1",
  "BINOPPRIORITY2",
  "BOOLCONST"
  };
}

